version: '3.3'

services:

  db:
    build: db
    image: xxx/xxx  [Replace with docker hub mentioned image]

  words:
    build: words
    image: xxx/xxx [Replace with docker hub mentioned image]
    deploy:
      replicas: 5

  web:
    build: web
    image: xxx/xxx  [Replace with docke hub mentined image]
    ports:
     - "8080:80"
